### ISSUE TITLE
Zen Kaku Gothic Antique のフォントちょっと気持ち悪くないですか？

### ISSUE THREAD

**Issue by Tonkyu** [Manato1fg/system-graduation-thesis-template#5]
<img width="1270" alt="SS- 2024-12-26 1 21 31" src="https://github.com/user-attachments/assets/d57e1f6b-26a2-4338-ac49-62b5812dd568" />

**Comment by Manato1fg** [comment]
確かに…？学術利用可能かつ無料なフォントでいいのあるのかな？

**Comment by Tonkyu** [comment]
Hiragino Kaku Gothic Pro結構良さげです．typst標準搭載だし学術利用も流石に大丈夫かな
![SS- 2024-12-26 2 11 23](https://github.com/user-attachments/assets/cc2ac06a-23e5-4639-b374-bbe613abb2bf)

**Comment by Tonkyu** [comment]
プルリクだしたいんだけど，どうもread-onlyでできないみたいので権限欲しいです！

**Comment by Manato1fg** [comment]
Collaboratorに招待したのでメール見て欲しい！
